cms: &cms
  adapter: <%= defined?(Mysql2) ? 'mysql2' : 'mysql' %>
  database: reactor
  username: reactoruser
  password: reactoruser
  host: reactordev
  reconnect: true

test:
  <<: *cms

development:
  <<: *cms
